name: Buildup Test

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build-and-release:
    runs-on: windows-2022  # 使用最新的 Windows 运行器

    steps:
      # 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Python 3.11 环境
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 安装依赖和 Nuitka
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python --version
        shell: cmd

      # 进行编译
      - name: Run Compile
        run: |
            python -m nuitka --windows-file-version=0.0.0.0 --show-progress --mingw64 --quiet --assume-yes-for-downloads --output-dir=out Boss-Key.py

      # 添加版本信息到可执行文件并重命名
      - name: Add version information and rename executable
        shell: pwsh
        run: |
          # 获取标签名作为版本号，去除前缀 refs/tags/
          $tag = 'Build-Test'
          # 定义新的文件名
          $newExeName = "Boss-Key-$tag-onefile.exe"
          
          # 重命名可执行文件
          Rename-Item "out/Boss-Key.exe" $newExeName

          # 压缩out/Boss-Key.dist/文件夹
          Compress-Archive -Path "out/Boss-Key.dist" -DestinationPath "out/Boss-Key-$tag-multifile.zip"

          ls out
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-Test-Build
          path: |
            out/Boss-Key-Build-Test-multifile.zip
