name: Compile to Installer-test

on: 
  workflow_dispatch:

jobs:
  compile-to-installer:
    runs-on: windows-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@v2
      
    - name: Clone Repo
      run: |
        cd ./.github/inno-script
        git clone https://github.com/IvanHanloth/innosetup-action.git
        cp -r innosetup-action/* .
        dir

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: Build-Test-Build

    - name: Extract zip 
      run: | 
        PowerShell -Command "Expand-Archive -Path 'Boss-Key-Build-Test-multifile.zip' -DestinationPath 'software'"

    - name: Compile Installer
      run: |
        dir
        .\ISCC.exe /DMyAppVersion='v2.0.0.0' Boss-Key.iss
      working-directory: .github/inno-script

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: Boss-Key-Installer
        path: .github/inno-script/output/Boss-Key-v2.0.0.0-Installer.exe
