name: Release Info Workflow and Deploy Jekyll with GitHub Pages

on:
  push:
    branches: ["main"]
  release:
    types: [published, edited, deleted]  # 在 release 创建、修改、删除时触发
  workflow_dispatch:  # 支持手动触发

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  fetch-and-sort-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 使用 Python 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Create Python script
        run: |
          cat << 'EOF' > fetch_releases.py
          import requests
          import json
          import os

          # GitHub API 地址
          repo = os.getenv('GITHUB_REPOSITORY')  # 获取当前仓库名称
          url = f'https://api.github.com/repos/{repo}/releases'

          # 请求头，使用 GITHUB_TOKEN 认证
          headers = {
              'Authorization': f'Bearer {os.getenv("GITHUB_TOKEN")}',
              'Accept': 'application/vnd.github.v3+json'
          }

          # 获取所有 release
          response = requests.get(url, headers=headers)
          if response.status_code != 200:
              raise Exception(f"Failed to fetch releases: {response.status_code} - {response.text}")

          releases = response.json()

          # 筛选需要的字段
          filtered_releases = []
          for release in releases:
              filtered_release = {
                  "tag_name": release["tag_name"],
                  "published_at": release["published_at"],
                  "body": release["body"],
                  "assets": [
                      {
                          "name": asset["name"],
                          "browser_download_url": asset["browser_download_url"]
                      }
                      for asset in release["assets"]
                  ]
              }
              filtered_releases.append(filtered_release)

          # 按时间顺序从旧到新排序
          sorted_releases = sorted(filtered_releases, key=lambda x: x['published_at'])

          # 将排序后的 release 信息保存为 JSON 文件
          with open('releases.json', 'w') as f:
              json.dump(sorted_releases, f, indent=2, ensure_ascii=False)

          print("Releases saved to releases.json")
          EOF

      - name: Run Python script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token 访问 API
        run: |
          python fetch_releases.py

      - name: Copy releases.json to _site directory
        run: |
          mkdir -p _site  # 创建 _site 目录（如果不存在）
          mv releases.json _site/releases.json  # 移动文件到 _site 目录

  build:
    runs-on: ubuntu-latest
    needs: fetch-and-sort-releases
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Copy additional files
        run: cp _site/releases.json ./_site/releases.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
